name: Lint

on:
  push:

jobs:

  get-go-version:
    name: "Get Go Version ğŸ¹"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout code ğŸ›’"
        uses: actions/checkout@v3

      - name: "Get Go version from 'go.mod' ğŸ“"
        id: get-go-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

  lint:
    name: "Lint Go code ğŸ¹"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout code ğŸ›’"
      uses: actions/checkout@v2
      
    - name: "Setup Go ğŸ¹"
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: "Install dependencies â¤µï¸"
      run: go mod download

    - name: "Run Go lint ğŸ‘“"
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.54
